### PR TITLE
Fix side comments in quotes

### LINKED ISSUE #42: Weird behavior of Side comments
I wrote a program to test the comment feature of YAML
* **The code**
```java
        // Create new YAML file with relative path
        saveResource("test.yml", true);
        final YamlFile yamlFile = new YamlFile(new File(getDataFolder(), "test.yml"));

        try {
            yamlFile.createOrLoadWithComments();
        } catch (final Exception e) {
            e.printStackTrace();
        }

        System.out.println("test-comment value: " + yamlFile.getString("test-comment"));
        System.out.println("test-comment side comment: " + yamlFile.getComment("test-comment", CommentType.SIDE));
        System.out.println("test-comment1 value: " + yamlFile.getString("test-comment1"));
        System.out.println("test-comment1 side comment: " + yamlFile.getComment("test-comment1", CommentType.SIDE));

        try {
            yamlFile.save();
        } catch (final IOException e) {
            e.printStackTrace();
        }
```
* **test.yml**
```yaml
test-comment: 'value' # comment
test-comment1: 'test# value2' # comment
```
* **Output**
```
test-comment value: value
test-comment side comment: comment
test-comment1 value: test# value2
test-comment1 side comment: value2'comment
```
* **test.yml** after running the code
```yaml
test-comment: value # comment
test-comment1: test# value2# value2' # comment
```
---
The **output** was supposed to be
```
test-comment value: value
test-comment side comment: comment
test-comment1 value: test# value2
test-comment1 side comment: comment
```
And **test.yml** should not be changed

### PR DESCRIPTION
**Pull request by LOOHP**
This PR fixes the side comment parser from matching '#' signs inside of single and double quotes.

Fixes #42

### CODE REVIEW

**Comment by Carleslc** [comment]
Hello, thank you for your interest in Simple-YAML. Is this PR working? I see you have more commits on your master branch. I pretend to fix the issue with side comments for the next minor release.

**Comment by LOOHP** [comment]
The solution on my master branch does kinda solve the issue but I found that it isn't quite stable. I've noticed some parsing errors that might or might not be related to the changes I made, therefore I closed the PR. I haven't gotten around to taking a closer look at it yet.

I also feel like it is probably best for someone with a better knowledge of SnakeYaml & SimpleYaml to deal with this.
Anyway, this bug is pretty much still around.

Here are a few test cases:
```yaml
Key: "This is a string with a # character inside of it" # actual comment
```
It will think that this is the comment "character inside of it" # actual comment"

```yaml
Key: "This is a string which got wrapped and also contains a #
    in its content."
```
Also, make sure that word wrapping is handled correctly.

**Comment by Carleslc** [comment]
Seems hard to solve with regex, I guess that is why you removed the side regex all the way.

I have added some failing tests for comments, including the test cases you describe. They are in the `fix-comments` branch that I'm going to use to develop this fix.

I have also created a branch `fix-comments-pr` with the changes of this PR rebased over the fix-comments branch.
With the changes of this PR some tests pass, but there are still some tests failing, so this PR will remain closed.

**Comment by Carleslc** [comment]
> Here are a few test cases:
> 
> ```yaml
> Key: "This is a string ''with a # character \"inside of it" # actual comment
> ```
> 
> It will think that this is the comment: `character inside of it" # actual comment` and the actual value will get cut off.
> 
> ```yaml
> Key: "This is a string\" \" which got ''wrapped and also contains a #
>     in its ''content."
> ```
> 
> Also, make sure when a fix is made, word wrapping is handled correctly. Especially when the wrapping happens right after a `#` character.

These test cases are now passing along with many other related test cases using the [1.8 release](https://github.com/Carleslc/Simple-YAML/releases/tag/1.8), see [test-comments4.yml](https://github.com/Carleslc/Simple-YAML/blob/master/Simple-Yaml/src/test/resources/test-comments4.yml)

**Pull request closed without merging**
