### PR TITLE
Corrected artifact group for maven & gradle.

### PR DESCRIPTION
**Pull request by AkramLZ**
Since it's a jitpack artifact, its group should start with `com.github.Carleslc` instead of `me.carleslc`

### CODE REVIEW

**Comment by Carleslc** [comment]
Both should work.
`me.carleslc` is a shorter, custom domain.
Does not work for you?

**Comment by frafol** [comment]
`me.carleslc` is not working for me

**Comment by Carleslc** [comment]
Related issue #77 to talk about this

**Comment by Carleslc** [comment]
> `me.carleslc` is not working for me

Should be working again.

**Comment by Carleslc** [comment]
Since it seems to be more stable, I'll use this as the default. I'll add a comment in the README that `me.carleslc.Simple-YAML` groupId is a valid alternative.

**Pull request merged**
