### PR TITLE
Unit test and general clean up (Simple-Yaml module)

### LINKED ISSUE #15: Reliable and more powerful unit testing.
ATM, the testing is not safe so much. We should add official unit test with jupiter and it should work when we build the project.
```xml
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter</artifactId>
    <version>5.6.2</version>
    <scope>test</scope>
</dependency>
```
Also, need a plugin;
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.22.2</version>
</plugin>
```
for automatic tests when the project is building.

### PR DESCRIPTION
**Pull request by portlek**
A simple unit test for `KeyTree` class.
More tests will be added.
Will close #15 (not yet)

### CODE REVIEW

**Comment by portlek** [comment]
@Carleslc alright Travis is working well, thanks.

**Comment by portlek** [comment]
@Carleslc the comment package's tests are done. The pull request is ready to merge. I will add more tests to other pull requests.

**Comment by portlek** [comment]
@Carleslc is there any problem with YamlConfiguration#parseHeader that method? Because my test can't pass it.

**Comment by portlek** [comment]
here is the code.
```java
@Test
void parseHeader() {
    final String content = "#test123\n" +
        "test:\n" +
        "  number: 5\n" +
        "  string: Hello world\n" +
        "  boolean: true\n" +
        "  list:\n" +
        "  - Each\n" +
        "  - word\n" +
        "  - will\n" +
        "  - be\n" +
        "  - in\n" +
        "  - a\n" +
        "  - separated\n" +
        "  - entry\n" +
        "math:\n" +
        "  pi: 3.141592653589793\n" +
        "timestamp:\n" +
        "  canonicalDate: 2020-07-04T13:18:04.458Z\n" +
        "  formattedDate: 04/07/2020 15:18:04\n";

    MatcherAssert.assertThat(
        "Couldn't parse the header of the content!",
        YamlConfiguration.parseHeader(content),
        new IsEqual<>("test123")
    );
}
```

**Comment by portlek** [comment]
Hmm, I found the problem but uhm;
image
When I add a space to my header its working because the build header method has this code;
image
So i think it can also support `#test123` although its just supporting `# test123`

**Comment by Carleslc** [comment]
Yes, I was checking also the same thing. `parseHeader` should be updated so it can handle comments without a leading space too.

**Comment by portlek** [comment]
> Yes, I was checking also the same thing. `parseHeader` should be updated so it can handle comments without a leading space too.

I open #28 to fix that issue.

**Comment by Carleslc** [comment]
I have added some tests to [example-tests](https://github.com/Carleslc/Simple-YAML/tree/example-tests) branch.

**YamlConfigurationOptions**
- pathSeparator
- indent
- charset
- isUnicode

**YamlFile**
- fileToString
- saveToString
- saveToStringWithComments
- getFilePath
- getConfigurationFile
- setConfigurationFile

**Comment by portlek** [comment]
Hmm, the latest build is working with Linux but not in Windows 10;
image
Windows's `readAllBytes` method is working different, it's adding \r thing end of line

**Comment by portlek** [comment]
@Carleslc I guess the simple-yaml module's tests are finished.

**Comment by Carleslc** [comment]
I've completed in https://github.com/Carleslc/Simple-YAML/commit/2520db270bf53a76946f7b3e52a90464222938ae the getSize test that was commented out, with other refactors, e.g. using temporary files to avoid polluting resources folder when not needed.

**Pull request merged**
